name: ci
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          username: meisterplanbuildserver
          password: ${{ secrets.DOCKER_HUB_API_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: meisterplan/actions-k8s-deploy:${{ github.ref_name }}
